# See https://docs.docker.com/compose/compose-file/ for information about what
# commands you can use in this file.
#
# Note that you must use the `docker stack deploy` command, with any required
# command line flags, in order to actually get any replicas started. That
# command requires that a docker swarm is already running in order to function.

version: "3"
services:
  startNode: 
    image: kadlab:latest
    stdin_open: true
    tty: true
    networks:
      kademlia_network:
        ipv4_address: 172.1.17.2
  kademliaNodes:
    image: kadlab:latest # Make sure your Docker image has this name.
    stdin_open: true
    tty: true
#   deploy:
#        restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3
#        window: 10s
    networks:
      - kademlia_network
    depends_on:    
      - startNode 
networks:
  kademlia_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.1.17.0/24
